package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/ACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/cygwin64/tmp/ojdkbuild/lookaside/java-1.8.0-openjdk/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Sunday, October 16, 2022 12:11:55 PM PDT
*/

public interface ACTIVE
{

  /** Object adapter state that indicates normal request processing.
   */
  public static final short value = (short)(1);
}
